version: '3.9'

services:
  db:
    image: mysql:8.4.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: db_aula
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
   build: .
   ports:
     - '3000:3000'
   environment:
     DB_HOST: db
     DB_USER: root
     DB_PASSWORD: ''
     DB_NAME: db_aula
   depends_on:
     - db

volumes:
  db_data:
